name: Deploy to FTP

on:
  push:
    branches:
      - main  # اگر شاخه اصلی شما نام دیگری دارد، آن را تغییر دهید

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # دستورات build پروژه شما مانند npm install و npm run build را در اینجا قرار دهید
          npm install
          npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
